import 'dart:typed_data';
import 'package:music_database/core/models/rola_data.dart';

List<RolaData> fakeRolas() => [
  RolaData(
    path: '/music/adroit_jazz.mp3',
    title: 'Adroit Jazz Underground',
    performer: 'The United States Of America',
    album: 'Avant Jazz',
    year: 2024,
    genre: 'Jazz',
    track: 1,
    audioHash: 'hash01',
    audioBytes: Uint8List(0),
    coverBytes: null,
  ),
  RolaData(
    path: '/music/antenne_bayern.mp3',
    title: 'Antenne Bayern',
    performer: 'Germany',
    album: 'Top40',
    year: 2023,
    genre: 'Pop',
    track: 1,
    audioHash: 'hash02',
    audioBytes: Uint8List(0),
    coverBytes: null,
  ),
  RolaData(
    path: '/music/bbc_world_service.mp3',
    title: 'BBC World Service',
    performer: 'United Kingdom',
    album: 'News',
    year: 2023,
    genre: 'News',
    track: 1,
    audioHash: 'hash03',
    audioBytes: Uint8List(0),
    coverBytes: null,
  ),
  RolaData(
    path: '/music/classic_vinyl_hd.mp3',
    title: 'Classic Vinyl HD',
    performer: 'USA',
    album: '1970‑80',
    year: 2022,
    genre: 'Rock',
    track: 7,
    audioHash: 'hash04',
    audioBytes: Uint8List(0),
    coverBytes: null,
  ),
  RolaData(
    path: '/music/dance_wave.mp3',
    title: 'Dance Wave!',
    performer: 'Hungary',
    album: 'Dance / House',
    year: 2024,
    genre: 'Dance',
    track: 3,
    audioHash: 'hash05',
    audioBytes: Uint8List(0),
    coverBytes: null,
  ),
  RolaData(
    path: '/music/hitradio_o3.mp3',
    title: 'ORF Hitradio Ö3',
    performer: 'Austria',
    album: 'Hits & Pop',
    year: 2024,
    genre: 'Pop',
    track: 12,
    audioHash: 'hash06',
    audioBytes: Uint8List(0),
    coverBytes: null,
  ),
  RolaData(
    path: '/music/radio_paradise.mp3',
    title: 'Radio Paradise (320k)',
    performer: 'California',
    album: 'Mix',
    year: 2023,
    genre: 'Mix',
    track: 5,
    audioHash: 'hash07',
    audioBytes: Uint8List(0),
    coverBytes: null,
  ),
];
